apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-jenkins
  labels:
    app: app-jenkins
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: app-jenkins
  template:
    metadata:
      labels:
        app: app-jenkins
    spec:
      containers:
        - name: jenkins
          image: nanuchavan037/jenkins:v1
          ports:
            - containerPort: 81  # The port your application listens on

apiVersion: v1
kind: Service
metadata:
  name: service-jenkins
spec:
  selector:
    app: app-jenkins  # Match the label to your Deployment
  ports:
    - protocol: TCP
      port: 81  # Port on which the service will be accessible
      targetPort: 80  # Port on which your application listens
type: NodePort
